import type { TEmployee } from "./types.ts";

export const employees: TEmployee[] = [
  {
    id: 1,
    full_name: "Иванова Татьяна Романовна",
    job_title: "Продуктовый менеджер",
    department_name: "Отдел спецпроектов",
    direction_name: "Соц. Франшиза",
    photo_url: "/src/shared/assets/images/avatar-1.png",
    status: "vacation",
    birthday_display: "01.01.2026",
    city: "Москва",
    tags: ["Английский (В2)", "Готов к командировкам"],
  },
  {
    id: 2,
    full_name: "Иванова Анна Сергеевна",
    job_title: "Ивент-менеджер",
    department_name: "Ивенты",
    direction_name: "СИС: Коммуникации",
    photo_url: "/src/shared/assets/images/avatar-2.png",
    status: "active",
    birthday_display: "01.01.2026",
    city: "Санкт-Петербург",
    tags: ["Английский (В2)", "Готов к командировкам"],
  },
  {
    id: 3,
    full_name: "Выборнова Яна Сергеевна",
    job_title: "Координатор обучения",
    department_name: "Центр подготовки",
    direction_name: "КСП с СПб",
    photo_url: "/src/shared/assets/images/avatar-1.png",
    status: "vacation",
    birthday_display: "01.01.2026",
    city: "Москва",
    tags: ["Английский (В2)", "Готов к командировкам"],
  },
  {
    id: 4,
    full_name: "Стремяков Михаил Иванович",
    job_title: "Руководитель региона",
    department_name: "Отдел регионального развития",
    direction_name: "Соц. Франшиза",
    photo_url: "/src/shared/assets/images/avatar-2.png",
    status: "active",
    birthday_display: "01.01.2026",
    city: "Москва",
    tags: ["Английский (В2)", "Готов к командировкам"],
  },
  {
    id: 5,
    full_name: "Маньшин Александр Олегович",
    job_title: "Методолог",
    department_name: "Методология и аудит",
    direction_name: "Центр экспертизы",
    photo_url: "/src/shared/assets/images/avatar-1.png",
    status: "vacation",
    birthday_display: "01.01.2026",
    city: "Уфа",
    tags: ["Английский (В2)", "Готов к командировкам"],
  },
  {
    id: 6,
    full_name: "Иванов Павел Викторович",
    job_title: "Менеджер по продажам",
    department_name: "Бизнес",
    direction_name: "Фандрайзинг и бизнес",
    photo_url: "/src/shared/assets/images/avatar-2.png",
    status: "active",
    birthday_display: "01.01.2026",
    city: "Казань",
    tags: ["Английский (В2)", "Готов к командировкам"],
  },
];

alert(
  "пока что не понятно, откуда берется поле city, в сваггере от бэка такого поля нет",
);
